### ISSUE TITLE
File referenced not included in repo

### ISSUE THREAD

**Issue by pjmolina** [mgechev/angular-lib-seed#1]
Hi. 
Just found a typo:
In **tsconfig.json** the file ["./lib/ngresizable.module.ts"](https://github.com/mgechev/angular-lib-seed/blob/master/tsconfig.json#L14) is referenced but not included in the repo.

I would add content under the `/lib` folder as a sample or remove this reference.

**Comment by mgechev** [comment]
Thanks for the catch!
